services:
  # FastAPI Application Service
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # PostgreSQL Database Service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME:-document_db}
      POSTGRES_USER: ${DB_USER:-myuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mypassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    command: ["postgres", "-c", "fsync=off"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 90s

# Define named volumes for data persistence
volumes:
  postgres_data:

# Define a custom bridge network
networks:
  app-network:
    driver: bridge
